{
 "title": "Carbon Emissions Transaction - Simple JDK 8 Application",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Software Carbon Intensity (SCI) in gCO2eq for Transaction method1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$ct+$Mt", "type": "math" }
   ]
  },
  {
   "title": "Software Carbon Intensity (SCI) in gCO2eq for Transaction method2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expression": "$ct+$Mt", "type": "math" }
   ]
  },
  {
   "title": "CPU Demand (ms) for the Test Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(io_retit_resource_demand_cpu_ms_milliseconds_total{job=\"simple-jdk8-application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Demand for the Whole Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(io_retit_emissions_java_process_cpu_time_total{job=\"simple-jdk8-application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Demand (bytes) for the Test Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(io_retit_resource_demand_memory_bytes_total{job=\"simple-jdk8-application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Emission Calculation Factors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "io_retit_emissions_cpu_power_min{job=\"simple-jdk8-application\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "io_retit_emissions_cpu_power_max{job=\"simple-jdk8-application\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "io_retit_emissions_embodied_emissions_minute_mg{job=\"simple-jdk8-application\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "io_retit_emissions_gef{job=\"simple-jdk8-application\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "io_retit_emissions_memory_energy_gb_minute{job=\"simple-jdk8-application\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "io_retit_emissions_network_energy_gb_minute{job=\"simple-jdk8-application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}