quarkus.http.port=8080
quarkus.package.jar.type=uber-jar

quarkus.package.jar.add-runner-suffix=false

quarkus.container-image.build=true
quarkus.jib.base-jvm-image=mirror.gcr.io/library/eclipse-temurin:21-jre
quarkus.container-image.image=quarkus-rest-service:feature

quarkus.otel.exporter.otlp.endpoint=http://host.docker.internal:4317
quarkus.application.name=quarkus-app
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=false