name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile and run Checkstyle, PMD and Spotbugs checks
        run: mvn -B checkstyle:check pmd:check compile spotbugs:check --file pom.xml
      - name: Package Extension and create Docker Container for Sample Application
        run: mvn -B package --file pom.xml
      - name: Run Integration Test
        run: mvn -B test -Dtest=JavaAgentExtensionIntegrationTest --file ./extension/pom.xml
      - name: Create Release and Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "extension/target/io.retit.opentelemetry.javaagent.extension.jar"